/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 public/models/aero-boy.gltf 
*/

import { useAnimations, useGLTF } from '@react-three/drei'
import React, { useEffect, useRef } from 'react'
import { useCharacterAnimations } from '../contexts/CharacterAnimations';

const AeroBoy = (props) => {
  const { nodes, materials, animations, scene } = useGLTF('./models/aero-boy.gltf')
  const group = useRef();
  const { setAnimations, animationIndex } = useCharacterAnimations();
  const { actions, names } = useAnimations(animations, group);

  useEffect(() => {
    setAnimations(names);
  }, [names]);

  useEffect(() => {
    const action = actions[names[animationIndex]];
    if (action) {
      action.reset().fadeIn(0.5).play();
    }
    return () => {
      if (action) {
        action.fadeOut(0.5);
      }
    };
  }, [animationIndex, actions, names]);

  return (
    <group ref={group} {...props} dispose={null}>
      <primitive object={scene} />
      <group name="AuxScene">
        <group name="Chicken_Dance" scale={0.01}>
          <primitive object={nodes.mixamorig6Hips} />
          <skinnedMesh
            castShadow
            receiveShadow
            bindMode="attached"
            name="Ch09"
            geometry={nodes.Ch09.geometry}
            material={materials.Ch09_body}
            skeleton={nodes.Ch09.skeleton}
          />
          <meshStandardMaterial
            castShadow
            receiveShadow
            {...materials.Ch09_body}
          />
        </group>
      </group>
    </group>
  )
}

export default AeroBoy
useGLTF.preload('./models/aero-boy.gltf')
