/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 public/models/ArcherKick.gltf 
*/

import { useAnimations, useGLTF } from '@react-three/drei'
import { useEffect, useRef } from 'react'
import { useCharacterAnimations } from '../contexts/CharacterAnimations';

export function ArcherKick(props) {
  const { nodes, materials, animations } = useGLTF('./models/ArcherKick.gltf')
  const group = useRef();
  const { setAnimations, animationIndex } = useCharacterAnimations();
  const { actions, names } = useAnimations(animations, group);

  useEffect(() => {
    setAnimations(names);
  }, [names]);

  useEffect(() => {
    const action = actions[names[animationIndex]];
    if (action) {
      action.reset().fadeIn(0.5).play();
    }
    return () => {
      if (action) {
        action.fadeOut(0.5);
      }
    };
  }, [animationIndex, actions, names]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="AuxScene">
        <group name="Mma_Kick" scale={0.01}>
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh castShadow name="Erika_Archer_Eyelashes_Mesh" geometry={nodes.Erika_Archer_Eyelashes_Mesh.geometry} material={materials.Body_MAT1} skeleton={nodes.Erika_Archer_Eyelashes_Mesh.skeleton} />
          <skinnedMesh castShadow name="Erika_Archer_Clothes_Mesh" geometry={nodes.Erika_Archer_Clothes_Mesh.geometry} material={materials.phong1} skeleton={nodes.Erika_Archer_Clothes_Mesh.skeleton} />
          <skinnedMesh castShadow name="Erika_Archer_Bow_Mesh" geometry={nodes.Erika_Archer_Bow_Mesh.geometry} material={materials.EyeSpec_MAT1} skeleton={nodes.Erika_Archer_Bow_Mesh.skeleton} />
          <skinnedMesh castShadow name="Erika_Archer_Arrow_Mesh" geometry={nodes.Erika_Archer_Arrow_Mesh.geometry} material={materials.Akai_MAT1} skeleton={nodes.Erika_Archer_Arrow_Mesh.skeleton} />
          <skinnedMesh castShadow name="Erika_Archer_Body_Mesh" geometry={nodes.Erika_Archer_Body_Mesh.geometry} material={materials.Bow_MAT} skeleton={nodes.Erika_Archer_Body_Mesh.skeleton} />
        </group>
      </group>
    </group>
  )
}

export default ArcherKick
useGLTF.preload('./models/ArcherKick.gltf')