/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 public/models/stacy.glb 
*/

import { useAnimations, useGLTF } from '@react-three/drei'
import React, { useRef } from 'react'

const Stacy = (props) => {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('./public/models/stacy.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Stacy" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh name="stacy" geometry={nodes.stacy.geometry} material={nodes.stacy.material} skeleton={nodes.stacy.skeleton} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
      </group>
    </group>
  )
}

export default Stacy
useGLTF.preload('./public/models/stacy.glb')
